name: confianza
description: "Confident - Red social anónima de videos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.6.2
  
  # Firebase
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.18.0
  firebase_storage: ^11.7.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.3
  
  # Media
  image_picker: ^1.1.2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
# Assets (imágenes, logos, etc)
  assets:
    - assets/images/logo.png