// File generated by FlutterFire CLI.
// This file configured by the user. Update this when you add a Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform;
import 'package:flutter/material.dart' show TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJaNJlIetOBbyMWs_9x7GwR6B70wQUej8',
    appId: '1:310977538437:web:xxxxxxxxxxxxxxxx',
    messagingSenderId: '310977538437',
    projectId: 'confident-f42af',
    authDomain: 'confident-f42af.firebaseapp.com',
    storageBucket: 'confident-f42af.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJaNJlIetOBbyMWs_9x7GwR6B70wQUej8',
    appId: '1:310977538437:android:c9825cd1b2746c0f92fcec',
    messagingSenderId: '310977538437',
    projectId: 'confident-f42af',
    storageBucket: 'confident-f42af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJaNJlIetOBbyMWs_9x7GwR6B70wQUej8',
    appId: '1:310977538437:ios:xxxxxxxxxxxxxxxx',
    messagingSenderId: '310977538437',
    projectId: 'confident-f42af',
    storageBucket: 'confident-f42af.firebasestorage.app',
    iosBundleId: 'com.confianza.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJaNJlIetOBbyMWs_9x7GwR6B70wQUej8',
    appId: '1:310977538437:ios:xxxxxxxxxxxxxxxx',
    messagingSenderId: '310977538437',
    projectId: 'confident-f42af',
    storageBucket: 'confident-f42af.firebasestorage.app',
    iosBundleId: 'com.confianza.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJaNJlIetOBbyMWs_9x7GwR6B70wQUej8',
    appId: '1:310977538437:windows:xxxxxxxxxxxxxxxx',
    messagingSenderId: '310977538437',
    projectId: 'confident-f42af',
    storageBucket: 'confident-f42af.firebasestorage.app',
    authDomain: 'confident-f42af.firebaseapp.com',
  );
}
